name: Testes

on:
  push:
    branches:
      - modulo-5-fernando
  pull_request:
    branches:
      - modulo-5-fernando

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          ref: modulo-5-fernando

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verificar requisitos
        run: |
          echo "Branch:"
          git branch --show-current
          echo "Commit:"
          git rev-parse HEAD
          echo "Arquivos:"
          ls -la
          echo "Requisitos:"
          find . -type f -name "requisitos.txt" -print

      - name: Instalar dependências
        run: pip install -r requisitos.txt

      - name: Testes do Executor
        run: PYTHONPATH=. pytest
